[project]
name = "sunbiz"
version = "0.1.0"
description = "Scraper Sunbiz corporation search"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "camoufox",
    "rich",
]

[tool.uv]
dev-dependencies = []
